# Setup File For HydroHub

# Teleport To Spawn On Server Join
gotoSpawnOnJoin: true
# Teleport To Spawn On Player Death
gotoSpawnOnDeath: true

# Adds a delay to /spawn if you want to.
spawnCommandDelay: true


# Chat Settings
# This sends a message when a member joins a lobby.
# The message can be changed in messages.yml
announcePlayerJoin: true

# This disables the default Minecraft join / leave messages.
disableDefaultJoinMessages: true


# The block which triggers the launch event. This can be GOLD_BLOCK or EMERALD_BLOCK. No pressure plate is needed.
boostPadBlock: 'EMERALD_BLOCK'

# Define Which Worlds Boost sPads Are Enabled On
boostPadWorlds:
  allowed:
    - hub
    - hub2
    - hub3
    - hub4

# Control how far the player is launched upon walking over a boost pad.
boostPadLaunchMultiplier: 2.0
boostPadHeightMultiplier: 1.0

# Scoreboard - To change messages, go to messages.yml !
scoreboardEnabled: true