# Setup File For HydroHub

# This is automatically filled when the command /setspawn has been run.
worldSpawnName:
worldSpawnX:
worldSpawnY:
worldSpawnZ:
worldSpawnYaw:
worldSpawnPitch:

# Teleport To Spawn On Server Join
gotoSpawnOnJoin: true
# Teleport To Spawn On Player Death
gotoSpawnOnDeath: true

# Adds a delay to /spawn if you want to.
spawnCommandDelay: true


# The block which triggers the launch event. This can be GOLD_BLOCK or EMERALD_BLOCK. No pressure plate is needed.
boostPadBlock: 'EMERALD_BLOCK'

# Define Which Worlds Boost sPads Are Enabled On
boostPadWorlds:
  allowed:
    - hub
    - hub2
    - hub3
    - hub4

# Control how far the player is launched upon walking over a boost pad.
boostPadLaunchMultiplier: 2.0
boostPadHeightMultiplier: 1.0